export const languageOptions = [
  {
    id: 63,
    name: "JavaScript",
    label: "JavaScript ",
    value: "javascript",
    extention: "js",
  },
  {
    id: 71,
    name: "Python (3.8.1)",
    label: "Python ",
    value: "python",
    extention: "py",
  },
  {
    id: 45,
    name: "Assembly (NASM 2.14.02)",
    label: "Assembly ",
    value: "assembly",
    extention: "asm",
  },
  // { id: 100, name: "html", label: "html", value: "html", extention: "html" },
  // { id: 101, name: "css", label: "css", value: "css", extention: "css" },
  // {
  //   id: 46,
  //   name: "Bash (5.0.0)",
  //   label: "Bash ",
  //   value: "bash",
  //   extention: "sh",
  // },
  // {
  //   id: 47,
  //   name: "Basic (FBC 1.07.1)",
  //   label: "Basic ",
  //   value: "basic",
  //   extention: "bas",
  // },
  // {
  //   id: 75,
  //   name: "C (Clang 7.0.1)",
  //   label: "C (Clang 7.0.1)",
  //   value: "c",
  // },
  // {
  //   id: 76,
  //   name: "C++ (Clang 7.0.1)",
  //   label: "C++ (Clang 7.0.1)",
  //   value: "cpp",
  // },
  // {
  //   id: 48,
  //   name: "C (GCC 7.4.0)",
  //   label: "C (GCC 7.4.0)",
  //   value: "c",
  // },
  // {
  //   id: 52,
  //   name: "C++ (GCC 7.4.0)",
  //   label: "C++ (GCC 7.4.0)",
  //   value: "cpp",
  // },
  // {
  //   id: 49,
  //   name: "C (GCC 8.3.0)",
  //   label: "C (GCC 8.3.0)",
  //   value: "c",
  // },
  // {
  //   id: 53,
  //   name: "C++ (GCC 8.3.0)",
  //   label: "C++ (GCC 8.3.0)",
  //   value: "cpp",
  // },
  {
    id: 50,
    name: "C (GCC 9.2.0)",
    label: "C ",
    value: "c",
    extention: "c",
  },
  {
    id: 54,
    name: "C++ (GCC 9.2.0)",
    label: "C++ ",
    value: "cpp",
    extention: "cpp",
  },
  // {
  //   id: 86,
  //   name: "Clojure (1.10.1)",
  //   label: "Clojure (1.10.1)",
  //   value: "clojure",
  //   extention: "clj",
  // },
  {
    id: 62,
    name: "Java (OpenJDK 13.0.1)",
    label: "Java ",
    value: "java",
    extention: "java",
  },
  {
    id: 51,
    name: "C# (Mono 6.6.0.161)",
    label: "C# ",
    value: "csharp",
    extention: "cs",
  },
  {
    id: 78,
    name: "Kotlin (1.3.70)",
    label: "Kotlin",
    value: "kotlin",
    extention: "kt",
  },
  {
    id: 43,
    label: "Plain Text",
    name: "Plain Text",
    value: "text",
    extention: "txt",
  },
  {
    id: 68,
    name: "PHP (7.4.1)",
    label: "PHP ",
    value: "php",
    extention: "php",
  },
  {
    id: 80,
    name: "R (4.0.0)",
    label: "R",
    value: "r",
    extention: "R",
  },
  {
    id: 72,
    name: "Ruby (2.7.0)",
    label: "Ruby ",
    value: "ruby",
    extention: "rb",
  },
  {
    id: 73,
    name: "Rust (1.40.0)",
    label: "Rust ",
    value: "rust",
    extention: "rs",
  },
  {
    id: 83,
    name: "Swift (5.2.3)",
    label: "Swift ",
    value: "swift",
    extention: "swift",
  },
  {
    id: 74,
    name: "TypeScript (3.7.4)",
    label: "TypeScript ",
    value: "typescript",
    extention: "ts",
  },
  {
    id: 77,
    name: "COBOL (GnuCOBOL 2.2)",
    label: "COBOL (GnuCOBOL 2.2)",
    value: "cobol",
    extention: "cob",
  },
  // {
  //   id: 55,
  //   name: "Common Lisp (SBCL 2.0.0)",
  //   label: "Common Lisp (SBCL 2.0.0)",
  //   value: "lisp",
  //   extention: "lisp",
  // },
  // {
  //   id: 56,
  //   name: "D (DMD 2.089.1)",
  //   label: "D (DMD 2.089.1)",
  //   value: "d",
  //   extention: "d",
  // },
  {
    id: 57,
    name: "Elixir (1.9.4)",
    label: "Elixir (1.9.4)",
    value: "elixir",
    extention: "ex",
  },
  {
    id: 58,
    name: "Erlang (OTP 22.2)",
    label: "Erlang (OTP 22.2)",
    value: "erlang",
    extention: "erl",
  },
  {
    id: 44,
    label: "Executable",
    name: "Executable",
    value: "exe",
    extention: "exe",
  },
  {
    id: 87,
    name: "F# (.NET Core SDK 3.1.202)",
    label: "F# ",
    value: "fsharp",
    extention: "fs",
  },
  {
    id: 59,
    name: "Fortran (GFortran 9.2.0)",
    label: "Fortran",
    value: "fortran",
    extention: "f90",
  },
  {
    id: 60,
    name: "Go (1.13.5)",
    label: "Go (1.13.5)",
    value: "go",
    extention: "go",
  },
  {
    id: 88,
    name: "Groovy (3.0.3)",
    label: "Groovy ",
    value: "groovy",
    extention: "groovy",
  },
  {
    id: 61,
    name: "Haskell (GHC 8.8.1)",
    label: "Haskell ",
    value: "haskell",
    extention: "hs",
  },

  {
    id: 64,
    name: "Lua (5.3.5)",
    label: "Lua ",
    value: "lua",
    extention: "lua",
  },

  // {
  //   id: 79,
  //   name: "Objective-C (Clang 7.0.1)",
  //   label: "Objective-C (Clang 7.0.1)",
  //   value: "objectivec",
  //   extention: "m",
  // },
  // {
  //   id: 65,
  //   name: "OCaml (4.09.0)",
  //   label: "OCaml (4.09.0)",
  //   value: "ocaml",
  //   extention: "ml",
  // },
  // {
  //   id: 66,
  //   name: "Octave (5.1.0)",
  //   label: "Octave (5.1.0)",
  //   value: "octave",
  //   extention: "m",
  // },
  {
    id: 67,
    name: "Pascal (FPC 3.0.4)",
    label: "Pascal ",
    value: "pascal",
    extention: "pas",
  },
  {
    id: 85,
    name: "Perl (5.28.1)",
    label: "Perl ",
    value: "perl",
    extention: "pl",
  },

  {
    id: 69,
    name: "Prolog (GNU Prolog 1.4.5)",
    label: "Prolog ",
    value: "prolog",
    extention: "pl",
  },
  // {
  //   id: 70,
  //   name: "Python (2.7.17)",
  //   label: "Python (2.7.17)",
  //   value: "python",
  // },

  {
    id: 81,
    name: "Scala (2.13.2)",
    label: "Scala ",
    value: "scala",
    extention: "scala",
  },
  // {
  //   id: 82,
  //   name: "SQL (SQLite 3.27.2)",
  //   label: "SQL (SQLite 3.27.2)",
  //   value: "sql",
  //   extention: ".sql",
  // },

  // {
  //   id: 84,
  //   name: "Visual Basic.Net (vbnc 0.0.0.5943)",
  //   label: "Visual Basic.Net (vbnc 0.0.0.5943)",
  //   value: "vbnet",
  //   extention: "vb",
  // },
];
